cd "${SPRING_DIR}"

rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"/bin-dir

cmake \
	-DCMAKE_TOOLCHAIN_FILE="/scripts/${PLATFORM}.cmake" \
	-DMARCH_FLAG="${MYARCHTUNE}" \
	-DCMAKE_CXX_FLAGS="${MYCFLAGS}" \
	-DCMAKE_C_FLAGS="${MYCFLAGS}" \
	-DCMAKE_CXX_FLAGS_RELWITHDEBINFO="${MYRWDIFLAGS}" \
	-DCMAKE_C_FLAGS_RELWITHDEBINFO="${MYRWDIFLAGS}" \
	-DCMAKE_BUILD_TYPE=RELWITHDEBINFO \
	-DAI_TYPES=NATIVE \
	-B "${BUILD_DIR}" \
	.
