// *** This is a generated file; if you want to change it, please change GlobalAIInterfaces.dll, which is the reference
// 
// This file was generated by CSAILoaderGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
   const char * get_myName()
   {
      return FeatureDef_get_myName( self );
   }

   const char * get_description()
   {
      return FeatureDef_get_description( self );
   }

   float get_metal()
   {
      return FeatureDef_get_metal( self );
   }

   float get_energy()
   {
      return FeatureDef_get_energy( self );
   }

   float get_maxHealth()
   {
      return FeatureDef_get_maxHealth( self );
   }

   float get_radius()
   {
      return FeatureDef_get_radius( self );
   }

   float get_mass()
   {
      return FeatureDef_get_mass( self );
   }

   bool get_upright()
   {
      return FeatureDef_get_upright( self );
   }

   int get_drawType()
   {
      return FeatureDef_get_drawType( self );
   }

   bool get_destructable()
   {
      return FeatureDef_get_destructable( self );
   }

   bool get_blocking()
   {
      return FeatureDef_get_blocking( self );
   }

   bool get_burnable()
   {
      return FeatureDef_get_burnable( self );
   }

   bool get_floating()
   {
      return FeatureDef_get_floating( self );
   }

   bool get_geoThermal()
   {
      return FeatureDef_get_geoThermal( self );
   }

   const char * get_deathFeature()
   {
      return FeatureDef_get_deathFeature( self );
   }

   int get_xsize()
   {
      return FeatureDef_get_xsize( self );
   }

   int get_ysize()
   {
      return FeatureDef_get_ysize( self );
   }

