// *** This is a generated file; if you want to change it, please change GlobalAIInterfaces.dll, which is the reference
// 
// This file was generated by CSAIProxyGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
   int GetNumBuildOptions(  )
   {
      return self->GetNumBuildOptions(   );
   }

   System::String * GetBuildOption( int index )
   {
      return new System::String( string( self->GetBuildOption( index  ) ).c_str() );
   }

   System::String * get_name()
   {
      return new System::String( string( self->get_name() ).c_str() );
   }

   System::String * get_humanName()
   {
      return new System::String( string( self->get_humanName() ).c_str() );
   }

   System::String * get_filename()
   {
      return new System::String( string( self->get_filename() ).c_str() );
   }

   int get_id()
   {
      return self->get_id();
   }

   int get_aihint()
   {
      return self->get_aihint();
   }

   int get_techLevel()
   {
      return self->get_techLevel();
   }

   double get_metalUpkeep()
   {
      return self->get_metalUpkeep();
   }

   double get_energyUpkeep()
   {
      return self->get_energyUpkeep();
   }

   double get_metalMake()
   {
      return self->get_metalMake();
   }

   double get_makesMetal()
   {
      return self->get_makesMetal();
   }

   double get_energyMake()
   {
      return self->get_energyMake();
   }

   double get_metalCost()
   {
      return self->get_metalCost();
   }

   double get_energyCost()
   {
      return self->get_energyCost();
   }

   double get_buildTime()
   {
      return self->get_buildTime();
   }

   double get_extractsMetal()
   {
      return self->get_extractsMetal();
   }

   double get_extractRange()
   {
      return self->get_extractRange();
   }

   double get_windGenerator()
   {
      return self->get_windGenerator();
   }

   double get_tidalGenerator()
   {
      return self->get_tidalGenerator();
   }

   double get_metalStorage()
   {
      return self->get_metalStorage();
   }

   double get_energyStorage()
   {
      return self->get_energyStorage();
   }

   double get_autoHeal()
   {
      return self->get_autoHeal();
   }

   double get_idleAutoHeal()
   {
      return self->get_idleAutoHeal();
   }

   int get_idleTime()
   {
      return self->get_idleTime();
   }

   double get_power()
   {
      return self->get_power();
   }

   double get_health()
   {
      return self->get_health();
   }

   double get_speed()
   {
      return self->get_speed();
   }

   double get_turnRate()
   {
      return self->get_turnRate();
   }

   int get_moveType()
   {
      return self->get_moveType();
   }

   bool get_upright()
   {
      return self->get_upright();
   }

   double get_controlRadius()
   {
      return self->get_controlRadius();
   }

   double get_losRadius()
   {
      return self->get_losRadius();
   }

   double get_airLosRadius()
   {
      return self->get_airLosRadius();
   }

   double get_losHeight()
   {
      return self->get_losHeight();
   }

   int get_radarRadius()
   {
      return self->get_radarRadius();
   }

   int get_sonarRadius()
   {
      return self->get_sonarRadius();
   }

   int get_jammerRadius()
   {
      return self->get_jammerRadius();
   }

   int get_sonarJamRadius()
   {
      return self->get_sonarJamRadius();
   }

   int get_seismicRadius()
   {
      return self->get_seismicRadius();
   }

   double get_seismicSignature()
   {
      return self->get_seismicSignature();
   }

   bool get_stealth()
   {
      return self->get_stealth();
   }

   double get_buildSpeed()
   {
      return self->get_buildSpeed();
   }

   double get_buildDistance()
   {
      return self->get_buildDistance();
   }

   double get_mass()
   {
      return self->get_mass();
   }

   double get_maxSlope()
   {
      return self->get_maxSlope();
   }

   double get_maxHeightDif()
   {
      return self->get_maxHeightDif();
   }

   double get_minWaterDepth()
   {
      return self->get_minWaterDepth();
   }

   double get_waterline()
   {
      return self->get_waterline();
   }

   double get_maxWaterDepth()
   {
      return self->get_maxWaterDepth();
   }

   double get_armoredMultiple()
   {
      return self->get_armoredMultiple();
   }

   int get_armorType()
   {
      return self->get_armorType();
   }

   System::String * get_type()
   {
      return new System::String( string( self->get_type() ).c_str() );
   }

   System::String * get_tooltip()
   {
      return new System::String( string( self->get_tooltip() ).c_str() );
   }

   System::String * get_wreckName()
   {
      return new System::String( string( self->get_wreckName() ).c_str() );
   }

   System::String * get_deathExplosion()
   {
      return new System::String( string( self->get_deathExplosion() ).c_str() );
   }

   System::String * get_selfDExplosion()
   {
      return new System::String( string( self->get_selfDExplosion() ).c_str() );
   }

   System::String * get_TEDClassString()
   {
      return new System::String( string( self->get_TEDClassString() ).c_str() );
   }

   System::String * get_categoryString()
   {
      return new System::String( string( self->get_categoryString() ).c_str() );
   }

   int get_selfDCountdown()
   {
      return self->get_selfDCountdown();
   }

   bool get_canfly()
   {
      return self->get_canfly();
   }

   bool get_canmove()
   {
      return self->get_canmove();
   }

   bool get_canhover()
   {
      return self->get_canhover();
   }

   bool get_floater()
   {
      return self->get_floater();
   }

   bool get_builder()
   {
      return self->get_builder();
   }

   bool get_activateWhenBuilt()
   {
      return self->get_activateWhenBuilt();
   }

   bool get_onoffable()
   {
      return self->get_onoffable();
   }

   bool get_reclaimable()
   {
      return self->get_reclaimable();
   }

   bool get_canRestore()
   {
      return self->get_canRestore();
   }

   bool get_canRepair()
   {
      return self->get_canRepair();
   }

   bool get_canReclaim()
   {
      return self->get_canReclaim();
   }

   bool get_canAttack()
   {
      return self->get_canAttack();
   }

   bool get_canPatrol()
   {
      return self->get_canPatrol();
   }

   bool get_canFight()
   {
      return self->get_canFight();
   }

   bool get_canGuard()
   {
      return self->get_canGuard();
   }

   bool get_canBuild()
   {
      return self->get_canBuild();
   }

   bool get_canAssist()
   {
      return self->get_canAssist();
   }

   bool get_canRepeat()
   {
      return self->get_canRepeat();
   }

   double get_wingDrag()
   {
      return self->get_wingDrag();
   }

   double get_wingAngle()
   {
      return self->get_wingAngle();
   }

   double get_drag()
   {
      return self->get_drag();
   }

   double get_frontToSpeed()
   {
      return self->get_frontToSpeed();
   }

   double get_speedToFront()
   {
      return self->get_speedToFront();
   }

   double get_myGravity()
   {
      return self->get_myGravity();
   }

   double get_maxBank()
   {
      return self->get_maxBank();
   }

   double get_maxPitch()
   {
      return self->get_maxPitch();
   }

   double get_turnRadius()
   {
      return self->get_turnRadius();
   }

   double get_wantedHeight()
   {
      return self->get_wantedHeight();
   }

   bool get_hoverAttack()
   {
      return self->get_hoverAttack();
   }

   double get_dlHoverFactor()
   {
      return self->get_dlHoverFactor();
   }

   double get_maxAcc()
   {
      return self->get_maxAcc();
   }

   double get_maxDec()
   {
      return self->get_maxDec();
   }

   double get_maxAileron()
   {
      return self->get_maxAileron();
   }

   double get_maxElevator()
   {
      return self->get_maxElevator();
   }

   double get_maxRudder()
   {
      return self->get_maxRudder();
   }

   int get_xsize()
   {
      return self->get_xsize();
   }

   int get_ysize()
   {
      return self->get_ysize();
   }

   int get_buildangle()
   {
      return self->get_buildangle();
   }

   double get_loadingRadius()
   {
      return self->get_loadingRadius();
   }

   int get_transportCapacity()
   {
      return self->get_transportCapacity();
   }

   int get_transportSize()
   {
      return self->get_transportSize();
   }

   bool get_isAirBase()
   {
      return self->get_isAirBase();
   }

   double get_transportMass()
   {
      return self->get_transportMass();
   }

   bool get_canCloak()
   {
      return self->get_canCloak();
   }

   bool get_startCloaked()
   {
      return self->get_startCloaked();
   }

   double get_cloakCost()
   {
      return self->get_cloakCost();
   }

   double get_cloakCostMoving()
   {
      return self->get_cloakCostMoving();
   }

   double get_decloakDistance()
   {
      return self->get_decloakDistance();
   }

   bool get_canKamikaze()
   {
      return self->get_canKamikaze();
   }

   double get_kamikazeDist()
   {
      return self->get_kamikazeDist();
   }

   bool get_targfac()
   {
      return self->get_targfac();
   }

   bool get_canDGun()
   {
      return self->get_canDGun();
   }

   bool get_needGeo()
   {
      return self->get_needGeo();
   }

   bool get_isFeature()
   {
      return self->get_isFeature();
   }

   bool get_hideDamage()
   {
      return self->get_hideDamage();
   }

   bool get_isCommander()
   {
      return self->get_isCommander();
   }

   bool get_showPlayerName()
   {
      return self->get_showPlayerName();
   }

   bool get_canResurrect()
   {
      return self->get_canResurrect();
   }

   bool get_canCapture()
   {
      return self->get_canCapture();
   }

   int get_highTrajectoryType()
   {
      return self->get_highTrajectoryType();
   }

   bool get_leaveTracks()
   {
      return self->get_leaveTracks();
   }

   double get_trackWidth()
   {
      return self->get_trackWidth();
   }

   double get_trackOffset()
   {
      return self->get_trackOffset();
   }

   double get_trackStrength()
   {
      return self->get_trackStrength();
   }

   double get_trackStretch()
   {
      return self->get_trackStretch();
   }

   int get_trackType()
   {
      return self->get_trackType();
   }

   bool get_canDropFlare()
   {
      return self->get_canDropFlare();
   }

   double get_flareReloadTime()
   {
      return self->get_flareReloadTime();
   }

   double get_flareDelay()
   {
      return self->get_flareDelay();
   }

   int get_flareTime()
   {
      return self->get_flareTime();
   }

   int get_flareSalvoSize()
   {
      return self->get_flareSalvoSize();
   }

   int get_flareSalvoDelay()
   {
      return self->get_flareSalvoDelay();
   }

   bool get_smoothAnim()
   {
      return self->get_smoothAnim();
   }

   bool get_isMetalMaker()
   {
      return self->get_isMetalMaker();
   }

   bool get_canLoopbackAttack()
   {
      return self->get_canLoopbackAttack();
   }

   bool get_levelGround()
   {
      return self->get_levelGround();
   }

   bool get_useBuildingGroundDecal()
   {
      return self->get_useBuildingGroundDecal();
   }

   int get_buildingDecalType()
   {
      return self->get_buildingDecalType();
   }

   int get_buildingDecalSizeX()
   {
      return self->get_buildingDecalSizeX();
   }

   int get_buildingDecalSizeY()
   {
      return self->get_buildingDecalSizeY();
   }

   double get_buildingDecalDecaySpeed()
   {
      return self->get_buildingDecalDecaySpeed();
   }

   bool get_isfireplatform()
   {
      return self->get_isfireplatform();
   }

   bool get_showNanoFrame()
   {
      return self->get_showNanoFrame();
   }

   bool get_showNanoSpray()
   {
      return self->get_showNanoSpray();
   }

   double get_maxFuel()
   {
      return self->get_maxFuel();
   }

   double get_refuelTime()
   {
      return self->get_refuelTime();
   }

   double get_minAirBasePower()
   {
      return self->get_minAirBasePower();
   }

