// *** This is a generated file; if you want to change it, please change GlobalAIInterfaces.dll, which is the reference
// 
// This file was generated by CSAIProxyGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
   int get_size()
   {
      return self->get_size();
   }

   double get_depth()
   {
      return self->get_depth();
   }

   double get_maxSlope()
   {
      return self->get_maxSlope();
   }

   double get_slopeMod()
   {
      return self->get_slopeMod();
   }

   double get_depthMod()
   {
      return self->get_depthMod();
   }

   int get_pathType()
   {
      return self->get_pathType();
   }

   double get_crushStrength()
   {
      return self->get_crushStrength();
   }

   int get_moveFamily()
   {
      return self->get_moveFamily();
   }

