        int GetCurrentFrame(  );
        int GetMyTeam(  );
        int GetMyAllyTeam(  );
        int GetPlayerTeam( int player );
        bool AddUnitToGroup( int unitid, int groupid );
        bool RemoveUnitFromGroup( int unitid );
        int GetUnitGroup( int unitid );
        int GetUnitAiHint( int unitid );
        int GetUnitTeam( int unitid );
        int GetUnitAllyTeam( int unitid );
        double GetUnitHealth( int unitid );
        double GetUnitMaxHealth( int unitid );
        double GetUnitSpeed( int unitid );
        double GetUnitPower( int unitid );
        double GetUnitExperience( int unitid );
        double GetUnitMaxRange( int unitid );
        bool IsUnitActivated( int unitid );
        bool UnitBeingBuilt( int unitid );
        int GetBuildingFacing( int unitid );
        bool IsUnitCloaked( int unitid );
        bool IsUnitParalyzed( int unitid );
        int GetMapWidth(  );
        int GetMapHeight(  );
        double GetMinHeight(  );
        double GetMaxHeight(  );
        double GetMaxMetal(  );
        double GetExtractorRadius(  );
        double GetMinWind(  );
        double GetMaxWind(  );
        double GetTidalStrength(  );
        double GetGravity(  );
        double GetElevation( double x, double z );
        double GetMetal(  );
        double GetMetalIncome(  );
        double GetMetalUsage(  );
        double GetMetalStorage(  );
        double GetEnergy(  );
        double GetEnergyIncome(  );
        double GetEnergyUsage(  );
        double GetEnergyStorage(  );
        double GetFeatureHealth( int feature );
        double GetFeatureReclaimLeft( int feature );
        int GetNumUnitDefs(  );
        double GetUnitDefRadius( int def );
        double GetUnitDefHeight( int def );
