import os

env = Environment(CPPPATH = ['.', '../../../rts', '../../../rts/System', '../../../rts/ExternalAI'])

env.SharedLibrary(os.path.abspath('../../../game/aidll/globalai/ntai'), Split('''
	Agents.cpp
	GlobalAI.cpp
	helper.cpp
	MetalHandler.cpp
	Interface.cpp
	UGroup.cpp
	Agents/Assigner.cpp
	Agents/Chaser.cpp
	Agents/Planning.cpp
	Agents/Register.cpp
	Agents/Scouter.cpp
	Helpers/Log.cpp
	Helpers/gui.cpp
'''))
