// *** This is a generated file; if you want to change it, please change CSAIInterfaces.dll, which is the reference
// 
// This file was generated by ABICCodeGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
AICALLBACK_API const char * FeatureDef_get_myName( const FeatureDef *self );
AICALLBACK_API const char * FeatureDef_get_description( const FeatureDef *self );
AICALLBACK_API float FeatureDef_get_metal( const FeatureDef *self );
AICALLBACK_API float FeatureDef_get_energy( const FeatureDef *self );
AICALLBACK_API float FeatureDef_get_maxHealth( const FeatureDef *self );
AICALLBACK_API float FeatureDef_get_radius( const FeatureDef *self );
AICALLBACK_API float FeatureDef_get_mass( const FeatureDef *self );
AICALLBACK_API bool FeatureDef_get_upright( const FeatureDef *self );
AICALLBACK_API int FeatureDef_get_drawType( const FeatureDef *self );
AICALLBACK_API bool FeatureDef_get_destructable( const FeatureDef *self );
AICALLBACK_API bool FeatureDef_get_blocking( const FeatureDef *self );
AICALLBACK_API bool FeatureDef_get_burnable( const FeatureDef *self );
AICALLBACK_API bool FeatureDef_get_floating( const FeatureDef *self );
AICALLBACK_API bool FeatureDef_get_geoThermal( const FeatureDef *self );
AICALLBACK_API const char * FeatureDef_get_deathFeature( const FeatureDef *self );
AICALLBACK_API int FeatureDef_get_xsize( const FeatureDef *self );
AICALLBACK_API int FeatureDef_get_ysize( const FeatureDef *self );
