// *** This is a generated file; if you want to change it, please change GlobalAIInterfaces.dll, which is the reference
// 
// This file was generated by CSAILoaderGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
   int get_size()
   {
      return MoveData_get_size( self );
   }

   float get_depth()
   {
      return MoveData_get_depth( self );
   }

   float get_maxSlope()
   {
      return MoveData_get_maxSlope( self );
   }

   float get_slopeMod()
   {
      return MoveData_get_slopeMod( self );
   }

   float get_depthMod()
   {
      return MoveData_get_depthMod( self );
   }

   int get_pathType()
   {
      return MoveData_get_pathType( self );
   }

   float get_crushStrength()
   {
      return MoveData_get_crushStrength( self );
   }

   int get_moveFamily()
   {
      return MoveData_get_moveFamily( self );
   }

