// *** This is a generated file; if you want to change it, please change GlobalAIInterfaces.dll, which is the reference
// 
// This file was generated by CSAILoaderGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
   int GetNumBuildOptions(  )
   {
      return UnitDef_GetNumBuildOptions( self   );
   }

   const char * GetBuildOption( int index )
   {
      return UnitDef_GetBuildOption( self , index  );
   }

   const char * get_name()
   {
      return UnitDef_get_name( self );
   }

   const char * get_humanName()
   {
      return UnitDef_get_humanName( self );
   }

   const char * get_filename()
   {
      return UnitDef_get_filename( self );
   }

   bool get_loaded()
   {
      return UnitDef_get_loaded( self );
   }

   int get_id()
   {
      return UnitDef_get_id( self );
   }

   const char * get_buildpicname()
   {
      return UnitDef_get_buildpicname( self );
   }

   int get_aihint()
   {
      return UnitDef_get_aihint( self );
   }

   int get_techLevel()
   {
      return UnitDef_get_techLevel( self );
   }

   float get_metalUpkeep()
   {
      return UnitDef_get_metalUpkeep( self );
   }

   float get_energyUpkeep()
   {
      return UnitDef_get_energyUpkeep( self );
   }

   float get_metalMake()
   {
      return UnitDef_get_metalMake( self );
   }

   float get_makesMetal()
   {
      return UnitDef_get_makesMetal( self );
   }

   float get_energyMake()
   {
      return UnitDef_get_energyMake( self );
   }

   float get_metalCost()
   {
      return UnitDef_get_metalCost( self );
   }

   float get_energyCost()
   {
      return UnitDef_get_energyCost( self );
   }

   float get_buildTime()
   {
      return UnitDef_get_buildTime( self );
   }

   float get_extractsMetal()
   {
      return UnitDef_get_extractsMetal( self );
   }

   float get_extractRange()
   {
      return UnitDef_get_extractRange( self );
   }

   float get_windGenerator()
   {
      return UnitDef_get_windGenerator( self );
   }

   float get_tidalGenerator()
   {
      return UnitDef_get_tidalGenerator( self );
   }

   float get_metalStorage()
   {
      return UnitDef_get_metalStorage( self );
   }

   float get_energyStorage()
   {
      return UnitDef_get_energyStorage( self );
   }

   float get_autoHeal()
   {
      return UnitDef_get_autoHeal( self );
   }

   float get_idleAutoHeal()
   {
      return UnitDef_get_idleAutoHeal( self );
   }

   int get_idleTime()
   {
      return UnitDef_get_idleTime( self );
   }

   float get_power()
   {
      return UnitDef_get_power( self );
   }

   float get_health()
   {
      return UnitDef_get_health( self );
   }

   float get_speed()
   {
      return UnitDef_get_speed( self );
   }

   float get_turnRate()
   {
      return UnitDef_get_turnRate( self );
   }

   int get_moveType()
   {
      return UnitDef_get_moveType( self );
   }

   bool get_upright()
   {
      return UnitDef_get_upright( self );
   }

   float get_controlRadius()
   {
      return UnitDef_get_controlRadius( self );
   }

   float get_losRadius()
   {
      return UnitDef_get_losRadius( self );
   }

   float get_airLosRadius()
   {
      return UnitDef_get_airLosRadius( self );
   }

   float get_losHeight()
   {
      return UnitDef_get_losHeight( self );
   }

   int get_radarRadius()
   {
      return UnitDef_get_radarRadius( self );
   }

   int get_sonarRadius()
   {
      return UnitDef_get_sonarRadius( self );
   }

   int get_jammerRadius()
   {
      return UnitDef_get_jammerRadius( self );
   }

   int get_sonarJamRadius()
   {
      return UnitDef_get_sonarJamRadius( self );
   }

   int get_seismicRadius()
   {
      return UnitDef_get_seismicRadius( self );
   }

   float get_seismicSignature()
   {
      return UnitDef_get_seismicSignature( self );
   }

   bool get_stealth()
   {
      return UnitDef_get_stealth( self );
   }

   float get_buildSpeed()
   {
      return UnitDef_get_buildSpeed( self );
   }

   float get_buildDistance()
   {
      return UnitDef_get_buildDistance( self );
   }

   float get_mass()
   {
      return UnitDef_get_mass( self );
   }

   float get_maxSlope()
   {
      return UnitDef_get_maxSlope( self );
   }

   float get_maxHeightDif()
   {
      return UnitDef_get_maxHeightDif( self );
   }

   float get_minWaterDepth()
   {
      return UnitDef_get_minWaterDepth( self );
   }

   float get_waterline()
   {
      return UnitDef_get_waterline( self );
   }

   float get_maxWaterDepth()
   {
      return UnitDef_get_maxWaterDepth( self );
   }

   float get_armoredMultiple()
   {
      return UnitDef_get_armoredMultiple( self );
   }

   int get_armorType()
   {
      return UnitDef_get_armorType( self );
   }

   const char * get_type()
   {
      return UnitDef_get_type( self );
   }

   const char * get_tooltip()
   {
      return UnitDef_get_tooltip( self );
   }

   const char * get_wreckName()
   {
      return UnitDef_get_wreckName( self );
   }

   const char * get_deathExplosion()
   {
      return UnitDef_get_deathExplosion( self );
   }

   const char * get_selfDExplosion()
   {
      return UnitDef_get_selfDExplosion( self );
   }

   const char * get_TEDClassString()
   {
      return UnitDef_get_TEDClassString( self );
   }

   const char * get_categoryString()
   {
      return UnitDef_get_categoryString( self );
   }

   const char * get_iconType()
   {
      return UnitDef_get_iconType( self );
   }

   int get_selfDCountdown()
   {
      return UnitDef_get_selfDCountdown( self );
   }

   bool get_canfly()
   {
      return UnitDef_get_canfly( self );
   }

   bool get_canmove()
   {
      return UnitDef_get_canmove( self );
   }

   bool get_canhover()
   {
      return UnitDef_get_canhover( self );
   }

   bool get_floater()
   {
      return UnitDef_get_floater( self );
   }

   bool get_builder()
   {
      return UnitDef_get_builder( self );
   }

   bool get_activateWhenBuilt()
   {
      return UnitDef_get_activateWhenBuilt( self );
   }

   bool get_onoffable()
   {
      return UnitDef_get_onoffable( self );
   }

   bool get_reclaimable()
   {
      return UnitDef_get_reclaimable( self );
   }

   bool get_canRestore()
   {
      return UnitDef_get_canRestore( self );
   }

   bool get_canRepair()
   {
      return UnitDef_get_canRepair( self );
   }

   bool get_canReclaim()
   {
      return UnitDef_get_canReclaim( self );
   }

   bool get_noAutoFire()
   {
      return UnitDef_get_noAutoFire( self );
   }

   bool get_canAttack()
   {
      return UnitDef_get_canAttack( self );
   }

   bool get_canPatrol()
   {
      return UnitDef_get_canPatrol( self );
   }

   bool get_canFight()
   {
      return UnitDef_get_canFight( self );
   }

   bool get_canGuard()
   {
      return UnitDef_get_canGuard( self );
   }

   bool get_canBuild()
   {
      return UnitDef_get_canBuild( self );
   }

   bool get_canAssist()
   {
      return UnitDef_get_canAssist( self );
   }

   bool get_canRepeat()
   {
      return UnitDef_get_canRepeat( self );
   }

   float get_wingDrag()
   {
      return UnitDef_get_wingDrag( self );
   }

   float get_wingAngle()
   {
      return UnitDef_get_wingAngle( self );
   }

   float get_drag()
   {
      return UnitDef_get_drag( self );
   }

   float get_frontToSpeed()
   {
      return UnitDef_get_frontToSpeed( self );
   }

   float get_speedToFront()
   {
      return UnitDef_get_speedToFront( self );
   }

   float get_myGravity()
   {
      return UnitDef_get_myGravity( self );
   }

   float get_maxBank()
   {
      return UnitDef_get_maxBank( self );
   }

   float get_maxPitch()
   {
      return UnitDef_get_maxPitch( self );
   }

   float get_turnRadius()
   {
      return UnitDef_get_turnRadius( self );
   }

   float get_wantedHeight()
   {
      return UnitDef_get_wantedHeight( self );
   }

   bool get_hoverAttack()
   {
      return UnitDef_get_hoverAttack( self );
   }

   float get_dlHoverFactor()
   {
      return UnitDef_get_dlHoverFactor( self );
   }

   float get_maxAcc()
   {
      return UnitDef_get_maxAcc( self );
   }

   float get_maxDec()
   {
      return UnitDef_get_maxDec( self );
   }

   float get_maxAileron()
   {
      return UnitDef_get_maxAileron( self );
   }

   float get_maxElevator()
   {
      return UnitDef_get_maxElevator( self );
   }

   float get_maxRudder()
   {
      return UnitDef_get_maxRudder( self );
   }

   int get_xsize()
   {
      return UnitDef_get_xsize( self );
   }

   int get_ysize()
   {
      return UnitDef_get_ysize( self );
   }

   int get_buildangle()
   {
      return UnitDef_get_buildangle( self );
   }

   float get_loadingRadius()
   {
      return UnitDef_get_loadingRadius( self );
   }

   int get_transportCapacity()
   {
      return UnitDef_get_transportCapacity( self );
   }

   int get_transportSize()
   {
      return UnitDef_get_transportSize( self );
   }

   bool get_isAirBase()
   {
      return UnitDef_get_isAirBase( self );
   }

   float get_transportMass()
   {
      return UnitDef_get_transportMass( self );
   }

   bool get_canCloak()
   {
      return UnitDef_get_canCloak( self );
   }

   bool get_startCloaked()
   {
      return UnitDef_get_startCloaked( self );
   }

   float get_cloakCost()
   {
      return UnitDef_get_cloakCost( self );
   }

   float get_cloakCostMoving()
   {
      return UnitDef_get_cloakCostMoving( self );
   }

   float get_decloakDistance()
   {
      return UnitDef_get_decloakDistance( self );
   }

   bool get_canKamikaze()
   {
      return UnitDef_get_canKamikaze( self );
   }

   float get_kamikazeDist()
   {
      return UnitDef_get_kamikazeDist( self );
   }

   bool get_targfac()
   {
      return UnitDef_get_targfac( self );
   }

   bool get_canDGun()
   {
      return UnitDef_get_canDGun( self );
   }

   bool get_needGeo()
   {
      return UnitDef_get_needGeo( self );
   }

   bool get_isFeature()
   {
      return UnitDef_get_isFeature( self );
   }

   bool get_hideDamage()
   {
      return UnitDef_get_hideDamage( self );
   }

   bool get_isCommander()
   {
      return UnitDef_get_isCommander( self );
   }

   bool get_showPlayerName()
   {
      return UnitDef_get_showPlayerName( self );
   }

   bool get_canResurrect()
   {
      return UnitDef_get_canResurrect( self );
   }

   bool get_canCapture()
   {
      return UnitDef_get_canCapture( self );
   }

   int get_highTrajectoryType()
   {
      return UnitDef_get_highTrajectoryType( self );
   }

   bool get_leaveTracks()
   {
      return UnitDef_get_leaveTracks( self );
   }

   float get_trackWidth()
   {
      return UnitDef_get_trackWidth( self );
   }

   float get_trackOffset()
   {
      return UnitDef_get_trackOffset( self );
   }

   float get_trackStrength()
   {
      return UnitDef_get_trackStrength( self );
   }

   float get_trackStretch()
   {
      return UnitDef_get_trackStretch( self );
   }

   int get_trackType()
   {
      return UnitDef_get_trackType( self );
   }

   bool get_canDropFlare()
   {
      return UnitDef_get_canDropFlare( self );
   }

   float get_flareReloadTime()
   {
      return UnitDef_get_flareReloadTime( self );
   }

   float get_flareEfficieny()
   {
      return UnitDef_get_flareEfficieny( self );
   }

   float get_flareDelay()
   {
      return UnitDef_get_flareDelay( self );
   }

   int get_flareTime()
   {
      return UnitDef_get_flareTime( self );
   }

   int get_flareSalvoSize()
   {
      return UnitDef_get_flareSalvoSize( self );
   }

   int get_flareSalvoDelay()
   {
      return UnitDef_get_flareSalvoDelay( self );
   }

   bool get_smoothAnim()
   {
      return UnitDef_get_smoothAnim( self );
   }

   bool get_isMetalMaker()
   {
      return UnitDef_get_isMetalMaker( self );
   }

   bool get_canLoopbackAttack()
   {
      return UnitDef_get_canLoopbackAttack( self );
   }

   bool get_levelGround()
   {
      return UnitDef_get_levelGround( self );
   }

   bool get_useBuildingGroundDecal()
   {
      return UnitDef_get_useBuildingGroundDecal( self );
   }

   int get_buildingDecalType()
   {
      return UnitDef_get_buildingDecalType( self );
   }

   int get_buildingDecalSizeX()
   {
      return UnitDef_get_buildingDecalSizeX( self );
   }

   int get_buildingDecalSizeY()
   {
      return UnitDef_get_buildingDecalSizeY( self );
   }

   float get_buildingDecalDecaySpeed()
   {
      return UnitDef_get_buildingDecalDecaySpeed( self );
   }

   bool get_isfireplatform()
   {
      return UnitDef_get_isfireplatform( self );
   }

   bool get_showNanoFrame()
   {
      return UnitDef_get_showNanoFrame( self );
   }

   bool get_showNanoSpray()
   {
      return UnitDef_get_showNanoSpray( self );
   }

   float get_maxFuel()
   {
      return UnitDef_get_maxFuel( self );
   }

   float get_refuelTime()
   {
      return UnitDef_get_refuelTime( self );
   }

   float get_minAirBasePower()
   {
      return UnitDef_get_minAirBasePower( self );
   }

