// *** This is a generated file; if you want to change it, please change GlobalAIInterfaces.dll, which is the reference
// 
// This file was generated by CSAILoaderGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
   float GetEnergyUsage(  )
   {
      return IAICallback_GetEnergyUsage( self   );
   }

   float GetEnergyStorage(  )
   {
      return IAICallback_GetEnergyStorage( self   );
   }

   float GetFeatureHealth( int feature )
   {
      return IAICallback_GetFeatureHealth( self , feature  );
   }

   float GetFeatureReclaimLeft( int feature )
   {
      return IAICallback_GetFeatureReclaimLeft( self , feature  );
   }

   int GetNumUnitDefs(  )
   {
      return IAICallback_GetNumUnitDefs( self   );
   }

   float GetUnitDefRadius( int def )
   {
      return IAICallback_GetUnitDefRadius( self , def  );
   }

   float GetUnitDefHeight( int def )
   {
      return IAICallback_GetUnitDefHeight( self , def  );
   }

   void SendTextMsg( char * text, int priority )
   {
      IAICallback_SendTextMsg( self , text, priority  );
   }

   int CreateGroup( char * dll, int aiNumber )
   {
      return IAICallback_CreateGroup( self , dll, aiNumber  );
   }

   void EraseGroup( int groupid )
   {
      IAICallback_EraseGroup( self , groupid  );
   }

   const char * GetModName(  )
   {
      return IAICallback_GetModName( self   );
   }

   const char * GetMapName(  )
   {
      return IAICallback_GetMapName( self   );
   }

   void SetFigureColor( int group, float red, float green, float blue, float alpha )
   {
      IAICallback_SetFigureColor( self , group, red, green, blue, alpha  );
   }

   void DeleteFigureGroup( int group )
   {
      IAICallback_DeleteFigureGroup( self , group  );
   }

   int GetCurrentFrame(  )
   {
      return IAICallback_GetCurrentFrame( self   );
   }

   int GetMyTeam(  )
   {
      return IAICallback_GetMyTeam( self   );
   }

   int GetMyAllyTeam(  )
   {
      return IAICallback_GetMyAllyTeam( self   );
   }

   int GetPlayerTeam( int player )
   {
      return IAICallback_GetPlayerTeam( self , player  );
   }

   bool AddUnitToGroup( int unitid, int groupid )
   {
      return IAICallback_AddUnitToGroup( self , unitid, groupid  );
   }

   bool RemoveUnitFromGroup( int unitid )
   {
      return IAICallback_RemoveUnitFromGroup( self , unitid  );
   }

   int GetUnitGroup( int unitid )
   {
      return IAICallback_GetUnitGroup( self , unitid  );
   }

   int GetUnitAiHint( int unitid )
   {
      return IAICallback_GetUnitAiHint( self , unitid  );
   }

   int GetUnitTeam( int unitid )
   {
      return IAICallback_GetUnitTeam( self , unitid  );
   }

   int GetUnitAllyTeam( int unitid )
   {
      return IAICallback_GetUnitAllyTeam( self , unitid  );
   }

   float GetUnitHealth( int unitid )
   {
      return IAICallback_GetUnitHealth( self , unitid  );
   }

   float GetUnitMaxHealth( int unitid )
   {
      return IAICallback_GetUnitMaxHealth( self , unitid  );
   }

   float GetUnitSpeed( int unitid )
   {
      return IAICallback_GetUnitSpeed( self , unitid  );
   }

   float GetUnitPower( int unitid )
   {
      return IAICallback_GetUnitPower( self , unitid  );
   }

   float GetUnitExperience( int unitid )
   {
      return IAICallback_GetUnitExperience( self , unitid  );
   }

   float GetUnitMaxRange( int unitid )
   {
      return IAICallback_GetUnitMaxRange( self , unitid  );
   }

   bool IsUnitActivated( int unitid )
   {
      return IAICallback_IsUnitActivated( self , unitid  );
   }

   bool UnitBeingBuilt( int unitid )
   {
      return IAICallback_UnitBeingBuilt( self , unitid  );
   }

   int GetBuildingFacing( int unitid )
   {
      return IAICallback_GetBuildingFacing( self , unitid  );
   }

   bool IsUnitCloaked( int unitid )
   {
      return IAICallback_IsUnitCloaked( self , unitid  );
   }

   bool IsUnitParalyzed( int unitid )
   {
      return IAICallback_IsUnitParalyzed( self , unitid  );
   }

   int GetMapWidth(  )
   {
      return IAICallback_GetMapWidth( self   );
   }

   int GetMapHeight(  )
   {
      return IAICallback_GetMapHeight( self   );
   }

   float GetMaxMetal(  )
   {
      return IAICallback_GetMaxMetal( self   );
   }

   float GetExtractorRadius(  )
   {
      return IAICallback_GetExtractorRadius( self   );
   }

   float GetMinWind(  )
   {
      return IAICallback_GetMinWind( self   );
   }

   float GetMaxWind(  )
   {
      return IAICallback_GetMaxWind( self   );
   }

   float GetTidalStrength(  )
   {
      return IAICallback_GetTidalStrength( self   );
   }

   float GetGravity(  )
   {
      return IAICallback_GetGravity( self   );
   }

   float GetElevation( float x, float z )
   {
      return IAICallback_GetElevation( self , x, z  );
   }

   float GetMetal(  )
   {
      return IAICallback_GetMetal( self   );
   }

   float GetMetalIncome(  )
   {
      return IAICallback_GetMetalIncome( self   );
   }

   float GetMetalUsage(  )
   {
      return IAICallback_GetMetalUsage( self   );
   }

   float GetMetalStorage(  )
   {
      return IAICallback_GetMetalStorage( self   );
   }

   float GetEnergy(  )
   {
      return IAICallback_GetEnergy( self   );
   }

   float GetEnergyIncome(  )
   {
      return IAICallback_GetEnergyIncome( self   );
   }

