
//#error WE ARE USING STREFLOP
#include "lib/streflop/streflop_cond.h"

#define FP_NAN STREFLOP_FP_NAN
#define FP_INFINITE STREFLOP_FP_INFINITE
#define FP_ZERO STREFLOP_FP_ZERO
#define FP_SUBNORMAL STREFLOP_FP_SUBNORMAL
#define FP_NORMAL STREFLOP_FP_NORMAL
