// *** This is a generated file; if you want to change it, please change CSAIInterfaces.dll, which is the reference
// 
// This file was generated by ABICCodeGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 
AICALLBACK_API int MoveData_get_size( const MoveData *self );
AICALLBACK_API float MoveData_get_depth( const MoveData *self );
AICALLBACK_API float MoveData_get_maxSlope( const MoveData *self );
AICALLBACK_API float MoveData_get_slopeMod( const MoveData *self );
AICALLBACK_API float MoveData_get_depthMod( const MoveData *self );
AICALLBACK_API int MoveData_get_pathType( const MoveData *self );
AICALLBACK_API float MoveData_get_crushStrength( const MoveData *self );
AICALLBACK_API int MoveData_get_moveFamily( const MoveData *self );
