// *** This is a generated file; if you want to change it, please change CSAIInterfaces.dll, which is the reference
// 
// This file was generated by MonoAbicWrappersGenerator, by Hugh Perkins hughperkins@gmail.com http://manageddreams.com
// 

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.IO;

namespace CSharpAI
{
    public class MoveData : MarshalByRefObject, IMoveData
    {
        public IntPtr self = IntPtr.Zero;
        public MoveData( IntPtr self )
        {
           this.self = self;
        }
      public System.Int32 size
      {
          get{ return ABICInterface.MoveData_get_size( self ); }
      }

      public System.Double depth
      {
          get{ return ABICInterface.MoveData_get_depth( self ); }
      }

      public System.Double maxSlope
      {
          get{ return ABICInterface.MoveData_get_maxSlope( self ); }
      }

      public System.Double slopeMod
      {
          get{ return ABICInterface.MoveData_get_slopeMod( self ); }
      }

      public System.Double depthMod
      {
          get{ return ABICInterface.MoveData_get_depthMod( self ); }
      }

      public System.Int32 pathType
      {
          get{ return ABICInterface.MoveData_get_pathType( self ); }
      }

      public System.Double crushStrength
      {
          get{ return ABICInterface.MoveData_get_crushStrength( self ); }
      }

      public System.Int32 moveFamily
      {
          get{ return ABICInterface.MoveData_get_moveFamily( self ); }
      }

#line 0 "AbicIMoveDataWrapper_manualtweaks.txt"


public MoveType moveType
{
    get
    {
        return (MoveType)ABICInterface.IMoveData_get_moveType( self );
    }
}


    }
}
